name: currency_app
description: A minimalist offline currency converter.
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.2
  google_mobile_ads: ^5.0.0
  url_launcher: ^6.1.12 
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.13.1"
  # --- MISSING DEPENDENCY ADDED HERE ---
  flutter_native_splash: ^2.3.3

# 1. APP ICON CONFIGURATION
flutter_launcher_icons:
  android: "final_icon"
  ios: true
  image_path: "assets/app_icon.png" 
  min_sdk_android: 21 
  remove_alpha_ios: true # <--- FIX: Removes transparency for iOS App Store compliance


# 2. SPLASH SCREEN CONFIGURATION (WAS MISSING)
flutter_native_splash:
  color: "#0d0d0d" # Background color
  image: "assets/splash_logo.png" # Center logo
  android_12:
    image: "assets/splash_logo.png"
    color: "#0d0d0d"

flutter:
  uses-material-design: true
  assets:
    - assets/